-- Real PO generation for the nightly auto-reorder loop.
--
-- supply_chain.generate_reorder_pos() is a stub: it returns vendor/location
-- summary groups but never creates POs ("Actual PO creation would be done by
-- calling application"). The calling application path (rpc_create_purchase_order)
-- requires auth.jwt(), which a cron has none of. This function does the real
-- insert with an explicit tenant id.
--
-- Semantics:
--   * One draft PO per (preferred_vendor_id, location_id) group from
--     inventory.v_reorder_suggestions.
--   * Items already on an open PO (any status other than cancelled/voided/
--     closed/fully_received) are skipped — no double-ordering.
--   * Idempotent per run: last_event_id = 'auto-reorder-{run}-{vendor}-{loc}'
--     with the existing UNIQUE (tenant_id, last_event_id); a rerun of the same
--     run id skips groups it already created (ON CONFLICT DO NOTHING).
--   * POs are created as 'draft' — the human approves/sends. Outbox events are
--     emitted by the existing row-level triggers on purchase_orders/_lines.

CREATE OR REPLACE FUNCTION supply_chain.rpc_generate_reorder_pos_v2(
  p_tenant_id UUID,
  p_run_id TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'supply_chain', 'inventory', 'public'
AS $$
DECLARE
  v_run TEXT := COALESCE(p_run_id, to_char(now(), 'YYYYMMDD'));
  v_group RECORD;
  v_sugg RECORD;
  v_po_id UUID;
  v_po_number TEXT;
  v_line_number INT;
  v_po_total NUMERIC;
  v_fallback_user UUID;
  v_created JSONB := '[]'::jsonb;
  v_skipped INT := 0;
BEGIN
  IF p_tenant_id IS NULL THEN
    RAISE EXCEPTION 'p_tenant_id is required';
  END IF;

  -- Machine-created rows still need an author; reuse the most recent PO creator.
  SELECT po.created_by_user_id INTO v_fallback_user
  FROM supply_chain.purchase_orders po
  WHERE po.tenant_id = p_tenant_id AND po.created_by_user_id IS NOT NULL
  ORDER BY po.created_at DESC
  LIMIT 1;

  FOR v_group IN
    SELECT rs.preferred_vendor_id AS vendor_id, rs.location_id
    FROM inventory.v_reorder_suggestions rs
    WHERE rs.tenant_id = p_tenant_id
      AND rs.preferred_vendor_id IS NOT NULL
      AND rs.suggested_order_qty > 0
      -- skip items already inbound on an open PO
      AND NOT EXISTS (
        SELECT 1
        FROM supply_chain.purchase_order_lines pol
        JOIN supply_chain.purchase_orders po ON po.id = pol.po_id
        WHERE po.tenant_id = p_tenant_id
          AND pol.catalog_item_id = rs.catalog_item_id
          AND po.status NOT IN ('cancelled', 'voided', 'closed', 'fully_received')
      )
    GROUP BY rs.preferred_vendor_id, rs.location_id
  LOOP
    v_po_number := supply_chain.generate_po_number(p_tenant_id);

    INSERT INTO supply_chain.purchase_orders (
      tenant_id, po_number, vendor_id, status,
      delivery_method, delivery_location_id, cost_context,
      order_date, needed_by_date, notes,
      created_by_user_id, vendor_name_snapshot, vendor_code_snapshot,
      last_event_id
    )
    SELECT
      p_tenant_id, v_po_number, v_group.vendor_id, 'draft',
      'ship', v_group.location_id, 'overhead',
      CURRENT_DATE, CURRENT_DATE + 7,
      'Auto-generated by nightly reorder (run ' || v_run || ')',
      v_fallback_user, v.name, v.code,
      'auto-reorder-' || v_run || '-' || v_group.vendor_id || '-' || v_group.location_id
    FROM supply_chain.vendors v
    WHERE v.id = v_group.vendor_id AND v.tenant_id = p_tenant_id
    ON CONFLICT (tenant_id, last_event_id) DO NOTHING
    RETURNING id INTO v_po_id;

    IF v_po_id IS NULL THEN
      v_skipped := v_skipped + 1;  -- already created by this run id
      CONTINUE;
    END IF;

    v_line_number := 0;
    v_po_total := 0;

    FOR v_sugg IN
      SELECT rs.catalog_item_id, rs.suggested_order_qty, rs.estimated_unit_cost
      FROM inventory.v_reorder_suggestions rs
      WHERE rs.tenant_id = p_tenant_id
        AND rs.preferred_vendor_id = v_group.vendor_id
        AND rs.location_id = v_group.location_id
        AND rs.suggested_order_qty > 0
        AND NOT EXISTS (
          SELECT 1
          FROM supply_chain.purchase_order_lines pol
          JOIN supply_chain.purchase_orders po ON po.id = pol.po_id
          WHERE po.tenant_id = p_tenant_id
            AND po.id <> v_po_id
            AND pol.catalog_item_id = rs.catalog_item_id
            AND po.status NOT IN ('cancelled', 'voided', 'closed', 'fully_received')
        )
      ORDER BY rs.catalog_item_id
    LOOP
      v_line_number := v_line_number + 1;
      INSERT INTO supply_chain.purchase_order_lines (
        tenant_id, po_id, line_number, catalog_item_id,
        qty_ordered, unit_cost, estimated_unit_cost, status, last_event_id
      ) VALUES (
        p_tenant_id, v_po_id, v_line_number, v_sugg.catalog_item_id,
        v_sugg.suggested_order_qty, v_sugg.estimated_unit_cost, v_sugg.estimated_unit_cost,
        'pending',
        'auto-reorder-' || v_run || '-' || v_po_id || '-' || v_line_number
      )
      ON CONFLICT (tenant_id, last_event_id) DO NOTHING;

      v_po_total := v_po_total
        + v_sugg.suggested_order_qty * COALESCE(v_sugg.estimated_unit_cost, 0);
    END LOOP;

    -- All of this group's items were claimed by an earlier PO in this run
    -- (same item suggested at several locations) — drop the empty shell.
    IF v_line_number = 0 THEN
      DELETE FROM supply_chain.purchase_orders WHERE id = v_po_id;
      CONTINUE;
    END IF;

    v_created := v_created || jsonb_build_object(
      'po_id', v_po_id,
      'po_number', v_po_number,
      'vendor_id', v_group.vendor_id,
      'location_id', v_group.location_id,
      'line_count', v_line_number,
      'estimated_total', v_po_total
    );
  END LOOP;

  RETURN jsonb_build_object(
    'run_id', v_run,
    'created', v_created,
    'created_count', jsonb_array_length(v_created),
    'skipped_existing', v_skipped
  );
END;
$$;
