-- ============================================================================
-- PHASE 8: TEST DATA HELPERS
-- ============================================================================
-- Functions to generate test data for verification

-- Helper to create test tenant
CREATE OR REPLACE FUNCTION inventory.create_test_tenant(
    p_tenant_name TEXT DEFAULT 'Test Tenant'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_tenant_id UUID;
BEGIN
    INSERT INTO public.tenants (name, last_event_id)
    VALUES (p_tenant_name, 'test_tenant_' || gen_random_uuid()::TEXT)
    ON CONFLICT (last_event_id) DO NOTHING
    RETURNING id INTO v_tenant_id;
    
    IF v_tenant_id IS NULL THEN
        SELECT id INTO v_tenant_id
        FROM public.tenants
        WHERE name = p_tenant_name
        LIMIT 1;
    END IF;
    
    RETURN v_tenant_id;
END;
$$;

-- Helper to create test location
CREATE OR REPLACE FUNCTION inventory.create_test_location(
    p_tenant_id UUID,
    p_location_name TEXT DEFAULT 'Test Warehouse'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_location_id UUID;
BEGIN
    INSERT INTO inventory.locations (
        tenant_id, 
        name, 
        location_type, 
        last_event_id
    )
    VALUES (
        p_tenant_id,
        p_location_name,
        'warehouse',
        'test_location_' || gen_random_uuid()::TEXT
    )
    ON CONFLICT (tenant_id, last_event_id) DO NOTHING
    RETURNING id INTO v_location_id;
    
    IF v_location_id IS NULL THEN
        SELECT id INTO v_location_id
        FROM inventory.locations
        WHERE tenant_id = p_tenant_id
        AND name = p_location_name
        LIMIT 1;
    END IF;
    
    RETURN v_location_id;
END;
$$;

-- Helper to create test item
CREATE OR REPLACE FUNCTION inventory.create_test_item(
    p_tenant_id UUID,
    p_sku TEXT DEFAULT NULL,
    p_name TEXT DEFAULT NULL,
    p_item_type TEXT DEFAULT 'stock'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_item_id UUID;
    v_sku TEXT;
    v_name TEXT;
BEGIN
    v_sku := COALESCE(p_sku, 'TEST-' || substring(gen_random_uuid()::TEXT from 1 for 8));
    v_name := COALESCE(p_name, 'Test Item ' || v_sku);
    
    INSERT INTO inventory.catalog_items (
        tenant_id,
        sku,
        name,
        item_type,
        last_event_id
    )
    VALUES (
        p_tenant_id,
        v_sku,
        v_name,
        p_item_type,
        'test_item_' || gen_random_uuid()::TEXT
    )
    ON CONFLICT (tenant_id, last_event_id) DO NOTHING
    RETURNING id INTO v_item_id;
    
    IF v_item_id IS NULL THEN
        SELECT id INTO v_item_id
        FROM inventory.catalog_items
        WHERE tenant_id = p_tenant_id
        AND sku = v_sku
        LIMIT 1;
    END IF;
    
    RETURN v_item_id;
END;
$$;

-- Helper to add stock (writes ledger)
CREATE OR REPLACE FUNCTION inventory.add_test_stock(
    p_tenant_id UUID,
    p_catalog_item_id UUID,
    p_location_id UUID,
    p_qty NUMERIC
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN inventory.insert_stock_movement(
        p_tenant_id => p_tenant_id,
        p_catalog_item_id => p_catalog_item_id,
        p_location_id => p_location_id,
        p_quantity_delta => p_qty,
        p_movement_type => 'received',
        p_source_ref_type => 'test_data',
        p_source_ref_id => NULL,
        p_unit_cost => 10.00,
        p_reason => 'Test data',
        p_notes => 'Generated by test helper',
        p_correlation_id => NULL,
        p_occurred_at => NOW(),
        p_created_by_user_id => NULL,
        p_last_event_id => 'test_stock_' || gen_random_uuid()::TEXT
    );
END;
$$;

-- Quick setup function
CREATE OR REPLACE FUNCTION inventory.setup_test_scenario()
RETURNS TABLE (
    tenant_id UUID,
    location_id UUID,
    item1_id UUID,
    item2_id UUID
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_tenant_id UUID;
    v_location_id UUID;
    v_item1_id UUID;
    v_item2_id UUID;
BEGIN
    -- Create tenant
    v_tenant_id := inventory.create_test_tenant('Epic Inventory Test');
    
    -- Create location
    v_location_id := inventory.create_test_location(v_tenant_id, 'Main Warehouse');
    
    -- Create items
    v_item1_id := inventory.create_test_item(v_tenant_id, 'WIDGET-100', 'Standard Widget', 'stock');
    v_item2_id := inventory.create_test_item(v_tenant_id, 'GADGET-200', 'Premium Gadget', 'stock');
    
    -- Add stock
    PERFORM inventory.add_test_stock(v_tenant_id, v_item1_id, v_location_id, 100);
    PERFORM inventory.add_test_stock(v_tenant_id, v_item2_id, v_location_id, 50);
    
    RETURN QUERY SELECT v_tenant_id, v_location_id, v_item1_id, v_item2_id;
END;
$$;

COMMENT ON FUNCTION inventory.setup_test_scenario IS 
    'Quick test data setup: tenant, location, 2 items with stock';

DO $$ BEGIN
    RAISE NOTICE '✅ Test data helper functions created';
END $$;

